# here am trying to do a ML and am separating data into train and testing also checking its performance


In [1]:
'''import dependences'''

import pandas as pd
import numpy as np
import sklearn


In [2]:
'''load data'''
data = pd.read_csv('mpg.csv')

In [3]:
data.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [4]:
data.tail() # to see last 

mpg  cylinders  displacement  horsepower  weight  acceleration  \
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin             name  
393          82     usa  ford mustang gl  
394          82  europe        vw pickup  
395          82     usa    dodge rampage  
396          82     usa      ford ranger  
397          82     usa       chevy s-10

In [5]:
data.drop('name',axis=1,inplace=True)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
mpg             398 non-null float64
cylinders       398 non-null int64
displacement    398 non-null float64
horsepower      392 non-null float64
weight          398 non-null int64
acceleration    398 non-null float64
model_year      398 non-null int64
origin          398 non-null object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB


In [7]:
'''geting the unique values to make categories'''

categories=[]
for i in data.origin.unique():
    categories.append(i)
    

In [8]:
categories

['usa', 'japan', 'europe']

In [9]:
data['new_origin']=pd.Categorical(data['origin'],categories=categories).codes

In [10]:
data.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin  new_origin  
0          70    usa           0  
1          70    usa           0  
2          70    usa           0  
3          70    usa           0  
4          70    usa           0

In [11]:
'''delete origin column'''

data.drop('origin',axis=1,inplace=True)

In [12]:
'''filling missing value'''
data=data.fillna(method='bfill')

In [13]:
data.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
new_origin      0
dtype: int64

In [14]:
len(data)

398

In [15]:
'''our data has total 398 lets seperate 300:98 as train and test 
 first ill do it manualy and next use function'''

X_train,X_test=data.drop('mpg',axis=1)[:300],data.drop('mpg',axis=1)[300:]

y_train,y_test=data['mpg'][:300],data['mpg'][300:]

In [16]:
'''lets import our model and train'''

from sklearn.linear_model import ARDRegression
Ard=ARDRegression()

In [17]:
Ard.fit(X_train,y_train)

ARDRegression(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, threshold_lambda=10000.0, tol=0.001, verbose=False)

In [18]:
Ard.predict(X_test)

array([16.84425109, 29.20091887, 28.42871448, 27.28177878, 29.4467399 ,
       26.40594945, 23.26427652, 22.53749591, 27.67781551, 29.22827142,
       28.15886747, 28.47078944, 28.86826253, 26.49344821, 25.91897794,
       24.85819185, 22.12141311, 28.57629942, 27.37319743, 27.60704919,
       27.44800603, 28.65179631, 28.18690572, 26.30502023, 27.59639648,
       28.18095098, 27.27247522, 25.86527509, 26.688579  , 29.89697068,
       28.73264945, 27.98917159, 30.02190105, 22.66434391, 29.66071526,
       28.13271426, 28.86356456, 28.06263363, 27.62838721, 27.31042069,
       27.60965511, 23.6837785 , 28.90025327, 29.48884746, 28.83352405,
       29.69992743, 28.39463686, 27.82016659, 29.00253164, 29.13610987,
       29.59103604, 28.84821646, 26.80414601, 29.92231839, 29.11938262,
       29.3298043 , 28.2396334 , 27.24422995, 27.63443175, 26.64911254,
       23.94441175, 23.65235884, 22.80265271, 22.23021729, 17.78472016,
       23.31512175, 23.77070619, 25.86685651, 26.32109438, 26.59

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(Ard,X_test,y_test,cv=4)

array([0.53534143, 0.49784093, 0.2529045 , 0.51783207])

In [21]:
'''result is not fair enough lets plot and see'''

import matplotlib.pyplot as plt

# plt.scatter(Ard.predict(X_test),y_test,color='r')
plt.plot(y_test,marker='o',color='r')
plt.show()


<Figure size 640x480 with 1 Axes>

In [22]:
'''impove its performance by changing the parameter'''

Ard=ARDRegression(normalize=True)

In [23]:
Ard.fit(X_train,y_train)

ARDRegression(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=True, threshold_lambda=10000.0, tol=0.001, verbose=False)

In [24]:
cross_val_score(Ard,X_test,y_test,cv=5)

array([0.74016462, 0.38690489, 0.58845783, 0.60022838, 0.39179575])

    ## better than previous one  lets try with different model

In [25]:
from sklearn.linear_model import HuberRegressor
Hu_reg=HuberRegressor()

In [26]:
Hu_reg.fit(X_train,y_train)

HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
        tol=1e-05, warm_start=False)

In [27]:
cross_val_score(Hu_reg,X_test,y_test,cv=5)

array([0.63280381, 0.32307461, 0.47765106, 0.55727743, 0.51489393])

#### HuberRegressor performs better than ARDregressor with default parameters lets try by altering the parameters 

In [28]:
Hu_reg=HuberRegressor(epsilon=1.54,max_iter=200,alpha=0.0004)

In [29]:
Hu_reg.fit(X_train,y_train)

HuberRegressor(alpha=0.0004, epsilon=1.54, fit_intercept=True, max_iter=200,
        tol=1e-05, warm_start=False)

In [30]:
cross_val_score(Hu_reg,X_test,y_test,cv=5)

array([0.66200747, 0.33393085, 0.47821209, 0.55551467, 0.58815432])